name: Build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    name: Build
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: fonimus/github-actions-tests/.github/workflows/reusable-build.yml@main
