name: Dump

on:
  create:
  delete:
  deployment:
  deployment_status:
  project:
  push:
  pull_request:
  discussion:
  pull_request_review:
  pull_request_review_comment:
  pull_request_target:
  watch:
  workflow_dispatch:
  workflow_call:
    inputs:
      project_name:
        default: ${{ github.event.repository.name }}
        required: false
        type: string
        description: Project name, used as prefix

jobs:
  test:
    name: Dump
    runs-on: ubuntu-latest
    steps:
      - name: Dump useful info
        run: |
          echo ${{ github.event.repository.name }}
          echo ${{ github.event_name }}
        shell: bash
      - name: Dump github context
        run: echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Dump github context in file
        run: echo "$GITHUB_CONTEXT" > github.env.json
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: github-env
          path: github.env.json
