name: Dump

on:
  create:
  delete:
  deployment:
  deployment_status:
  project:
  push:
  pull_request:
  discussion:
  pull_request_review:
  pull_request_review_comment:
  pull_request_target:
  watch:
  workflow_dispatch:

jobs:
  test:
    name: Dump
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context
        run: echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
