name: Pull Request Labeler

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: false
        description: Github token to be able to modify pull request
  pull_request:
    types: [opened]

jobs:
  pr-labeler:
    name: Pull Request Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
