name: PR Labeler

on:
  pull_request:
    types: [opened]

jobs:
  pr-labeler:
    name: PR Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
