name: Publish Release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    name: Publish ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create changelogs
        id: changelogs
        uses: heineiuo/create-changelogs@v0.2.8

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelogs.outputs.changelogs }}
          draft: false
          prerelease: ${{ steps.changelogs.outputs.release_type == 'prerelease' }}
