name: Publish Release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    name: Publish ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Is Pre Release ?
        id: pre_release
        uses: heineiuo/create-changelogs@v0.2.8

      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          configuration: .changelog-generator.json
          ignorePreReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          
      - name: Create Release
        id: create-release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: ${{ steps.pre_release.outputs.release_type == 'prerelease' }}
          
      - name: Update CHANGLOG.md
        run: |
          echo ${{ github.ref }}
          echo ${{ github.repository }}
          export changeLog=$(echo ${{ steps.changelog.outputs.changelog }} | sed -e "s/##/###/g")
          export toImport="## [${{ github.ref }}](https://github.com/${{ github.repository }}/releases/tag/${{ github.ref }})\n\n$changeLog"
          echo $toImport
          sed "/^##/i $toImport\n" CHANGELOG.md
          cat CHANGELOG.md
          
          
