name: Test

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

env:
  TEST: test from env
  ENV_VAR_1: var1
  ENV_VAR_2: ${{ env.ENV_VAR_1 }}

jobs:
  before:
    name: Before
    runs-on: ubuntu-latest
    steps:
      - name: Dump useful info
        run: |
          echo "Env var 1: ${{ env.ENV_VAR_1 }}"
          echo "Env var 2: ${{ env.ENV_VAR_2 }}"
  build:
    name: Test
    uses: fonimus/github-actions-tests/.github/workflows/dump.yml@main
    with:
      other_input: "$TEST"
